notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

env:
  - BUILD_ELEMENT='docker'
  - BUILD_ELEMENT='validate'

services:
  - docker

install:
 - docker build -t dockstore-cgpmap .
 - virtualenv -p python3 venv
 - source venv/bin/activate
 - pip install html5lib cwltool

script:
 - 'set -ue
    if [ "$BUILD_ELEMENT" == "docker" ]; then
      docker images | grep -c dockstore-cgpmap
    elif [ "$BUILD_ELEMENT" == "validate" ]; then
      cwltool --validate Dockstore.cwl
      cwltool --validate cwls/cgpmap-bamOut.cwl
      cwltool --validate cwls/cgpmap-cramOut.cwl
    fi'
