notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

env:
  - BUILD_ELEMENT='docker'
  - BUILD_ELEMENT='validate'

services:
  - docker

install:
 - docker build -t dockstore-cgpmap .
 - virtualenv -p python3 venv
 - source venv/bin/activate
 - pip install html5lib cwltool

script:
 - set -ue
 - if [ "$BUILD_ELEMENT" == "docker" ] bash -c 'docker images | grep -c dockstore-cgpmap'
 - if [ "$BUILD_ELEMENT" == "validate" ] \
    cwltool --validate Dockstore.cwl && \
    cwltool --validate cwls/cgpmap-bamOut.cwl && \
    cwltool --validate cwls/cgpmap-cramOut.cwl
